### ISSUE TITLE
Slow batch labelling

### ISSUE THREAD

**Issue by davidrs** [faustomorales/qsl#1]
**Request: ** Stable Support for a larger number of items OR guidance on a good max.

I added 18k s3:// image paths and labelling ended up being very slow and a little unreliable (UI getting in stuck states)
The act of labelling 10 goes pretty slowly specifically during the  update to the DB and load the new images.

Using the UI to add this many was also slow, being able to provide a txt file with URLs would be nice, Chrome almost froze twice with the large copy paste.

I've realized I only really want to label 5k anyway, so I'm about to retry with 5k and will report back on the experience. Then the fix may be suggested max per project.

(I was using it running on EC2 with portforwarded to my local machine, I don't expect this to be the cause, but for complete info)

**Comment by davidrs** [comment]
I tried a new project with only ~250 labels and deleted the old project of 18k.
It is still very slow, aprox 3 seconds waiting between batches.

Setup is:
- 250 s3:// image links
- QSL running on an AWS EC2 box, 5000 port forwarded to my laptop.
- batch labelling with batch size of 20

Ideas:
- the delete of the old project didn't clear the DB space / had some lingering effect.
- s3 is not that fast.

Next step:
- I'll try a new project and use local file paths and see how quickly it goes to try and bisect DB interactions from image laod times

**Comment by davidrs** [comment]
Turns out EC2 port forwarding is the issue, running it locally with S3 is twice as fast, down to aprox 1.5-2seconds, but still slower than using a local file viewer.

A further improvement to get batches more instantaneous would be to load the next batch into the DOM, but with a css visibility of none, and then as soon as the previous batch is submitted set the visibility to true.  This should make it pretty much instant

**Comment by davidrs** [comment]
Turns out batching did not yet have pre-fetching fix incoming

**Comment by faustomorales** [comment]
Closing as part of refactor into widgets.
