### ISSUE TITLE
Feature: add label to index view

### ISSUE THREAD

**Issue by davidrs** [faustomorales/qsl#12]
It would be nice to be able to see / filter by label values on index screen.
Our specific use case it quickly pulling up images that were tagged as 'unsure' to rereview as a group.

![image](https://user-images.githubusercontent.com/1407489/207941752-da05de5d-598b-4e25-af90-e867b5db1777.png)

Since labelling configs could have multiple label configuration and types I understand this would not be trivial to have a good universal solution.
Initial Ideas:
- Filtering just does a plain string search of the label blobs.

Current work arounds are either for us to do it outside of QSL, or instruct labellers to 'skip' labelling those images,  have to make assumptions to disambiguate skipped due to running out of time, vs skipped due to user error vs skipped due to `unsure` label.

**Comment by faustomorales** [comment]
Sure, I've done a first-pass at this in f6b8b930a7673d89a2e3f6dc426559a16495a6e5, which you can now use by upgrading to version v0.2.22. It uses semicolons to separate different labeling categories and commas to separate multiple labels for the same category. Quick and dirty but I think it works.

```python
import qsl
import qsl.testing

qsl.MediaLabeler(
     items=[
        {"target": qsl.testing.files.TEST_IMAGES[0], "labels": {"image": {"Keep": ["Yes"], "Quality": ["High"]}}},
        {"target": qsl.testing.files.TEST_IMAGES[1], "labels": {"image": {"Keep": ["No"], "Quality": ["Low"]}}},
        {"target": qsl.testing.files.TEST_IMAGES[2], "labels": {"image": {"Keep": ["Unsure"]}}},
    ],
    config={
        "image": [
            {"name": "Keep", "options": [
                {"name": "Yes"},
                {"name": "No"},
                {"name": "Unsure"}
            ]},
            {"name": "Quality", "options": [
                {"name": "High"},
                {"name": "Low"},
            ]},
        ],
        "regions": []
    },
)
```

<img width="560" alt="image" src="https://user-images.githubusercontent.com/9735401/208152446-900580bf-fca8-4668-843e-82df8ac0f15f.png">

And you can now filter by whether a string appears anywhere with the target column. Sorry about the overlapping UI elements here, someday I'll find the time to polish up the index table UI component so this doesn't happen. 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/9735401/208152824-60218198-c779-4dd2-8ced-2cfd4a1fbd28.png">

Closing this for now, but feel free to reopen if it doesn't work.
