### ISSUE TITLE
Pagination does not reset when filtering results on the View Index page

### ISSUE THREAD

**Issue by erinspace** [faustomorales/qsl#13]
Hi Fausto! What a great tool! I dunno if this falls under bug, quirk that needs some call out in the docs, or something else, but it was enough to cause some (mild) panic that filtering wasn't going to work until we figured out what was happening!

## Description

On the "View Index" page, if your filtered results are fewer than what would show on the page you're currently viewing, it looks like there are zero filtered results. To view filtered results, you need to manually page back to a page that is low enough to contain the number of results that are in your filter.

## Reproduction

- Label enough images so that you have multiple pages in the "View Index" window
    -  in my testing this was more than 7 images
- Click the "View Index" button, notice you're on a high page number
- Filter for a term that has less than 7 results (or few enough to not make it to the page you're on)
- Notice that it looks like there are no results for the filter
- Page backwards a few times, and there are your results!

![qsl_filter_quirk](https://user-images.githubusercontent.com/801594/214059608-8dfce4c5-c909-4e22-a5f8-b1cc9d597b9f.gif)

**Comment by faustomorales** [comment]
Thanks for raising this! It's solved in 6f39caf. The code I wrote for the index page is ... truly horrible. :/ But it seems to work so I suppose we'll just keep on trucking!
