### ISSUE TITLE
Images not showing up when batch labelling

### ISSUE THREAD

**Issue by ayushi-bureau** [faustomorales/qsl#17]
I am able to view images when batchSize is set to 1. But, when increased to anything above 1, images are not getting displayed. Here's a google colab notebook where the bug can be observed - https://colab.research.google.com/drive/1YyuJW-6s_xHvssIJ-Cc5O6Aooh0GJ63O?usp=sharing#scrollTo=sStB-wQuRYrR

**Comment by faustomorales** [comment]
Thanks for raising this! It's fixed now in v0.2.33, as demonstrated in [this colab](https://colab.research.google.com/drive/1ExrSIJdvW96D2h1tvJxntyhqFmuZoMfu?usp=sharing) (it's the same as the one you posted but pinned to 0.2.33).
