### ISSUE TITLE
Unclear how to force it to use `Sliding Target Batch Size`

### ISSUE THREAD

**Issue by davidrs** [faustomorales/qsl#2]
When in batch labelling and I  change the `Target Batch Size` it doesn't do anything until you submit the page, and sometimes it takes another submit.

Not completely clear what triggers it to take effect. Things I tried
- Using the arrow keys to go to the next batch and back does not change the batch size.
- Refreshing the page removes all the settings

After using 'enter' to save and progress twice the new batch size took effect.

**ideally**: 
- changing the slider would instantly load more or fewer images, but I could see that being a pain with the static urls. If it forced a page reload I'd be ok with that
- Would be nice if it remembered my batch sizes between leaving the batch review page and coming back.

**Comment by davidrs** [comment]
I've also noticed when it took effect on the third batch it showed me images that it already showed me in batch 1 and had been labelled. (i confirmed same IDs in the url, not just look alike images)

**Comment by davidrs** [comment]
Code fetches the next batch when the first set loads, so the slider only effects the batch after that.

Fix would be to update the `useEffect` that does the `nextBatchesQuery` to also run on slider changes eg when `navstate.batchsize` changes. Would need to look for side effects.

**Comment by faustomorales** [comment]
Closing as part of refactor into widgets where batch size is set as an argument.
