### ISSUE TITLE
UI hangs on last batch

### ISSUE THREAD

**Issue by davidrs** [faustomorales/qsl#3]
When I labelled the last 9 and hit enter UI stayed at 87% and did not show a new batch or anything and did not go to 100%
![image](https://user-images.githubusercontent.com/1407489/114055974-10af7900-9846-11eb-90f9-3c993840c536.png)

It looked/felt like it was hitting an error

Confirmed all labels are done:
![image](https://user-images.githubusercontent.com/1407489/114056131-33da2880-9846-11eb-8a42-ebb2517fc168.png)

**ideally:**
- After labelling the last batch to progress updates to 100%.
- Some UI message "Labelling complete. click here to return to the project page"

**Comment by faustomorales** [comment]
Closing as part of refactor into widgets.
